// Generates migrations/0002_seed_content.sql from src/data/lessonData.js.
// Run: npm run seed:build
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual } from "node:util";
import lessonData from "../src/data/lessonData.js";
import { validateTopic, findDuplicateExerciseIds } from "../src/shared/validateTopic.js";

const outFile = fileURLToPath(new URL("../migrations/0002_seed_content.sql", import.meta.url));
const SEED_TIME = "2026-01-01T00:00:00.000Z";

// SQLite string literal: only the single quote needs escaping (doubled).
// Backslashes, newlines and emoji are literal inside '...'.
function sqlString(value) {
    return "'" + String(value).replace(/'/g, "''") + "'";
}

const problems = [];
lessonData.forEach(topic => {
    const result = validateTopic(topic);
    if (!result.ok) problems.push(`${topic.slug}: ${result.errors.join("; ")}`);
});
for (const dup of findDuplicateExerciseIds(lessonData)) {
    problems.push(`exercise id ${dup.id} used in ${dup.topics.join(" and ")}`);
}
if (problems.length > 0) {
    console.error("Bundled content is invalid:\n" + problems.join("\n"));
    process.exit(1);
}

const lines = [
    "-- GENERATED by scripts/build-seed.mjs from src/data/lessonData.js. Do not edit.",
    "-- INSERT OR IGNORE: never overwrites topics already edited in the admin panel.",
    ""
];

lessonData.forEach((topic, position) => {
    const json = JSON.stringify(topic);
    lines.push(
        "INSERT OR IGNORE INTO topics (slug, position, data, updated_at) VALUES (" +
        [sqlString(topic.slug), position, sqlString(json), sqlString(SEED_TIME)].join(", ") +
        ");"
    );
});

writeFileSync(outFile, lines.join("\n") + "\n", "utf8");

// Round-trip check: undo the escaping and compare with the source data.
const written = readFileSync(outFile, "utf8");
const literal = /^INSERT OR IGNORE INTO topics \(slug, position, data, updated_at\) VALUES \('((?:[^']|'')*)', (\d+), '((?:[^']|'')*)', '[^']*'\);$/gm;
const parsed = [...written.matchAll(literal)].map(m => JSON.parse(m[3].replace(/''/g, "'")));
if (!isDeepStrictEqual(parsed, lessonData)) {
    console.error("Round-trip check failed.");
    process.exit(1);
}

console.log(`Wrote ${lessonData.length} topics to ${outFile}`);
